name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - name: Restore
        run: dotnet tool restore
      - name: Paket install
        run: dotnet paket install
      - name: Build
        run: dotnet fake build -t TestsRun
